//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.HomeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeService.IHomeService")]
    public interface IHomeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetLength", ReplyAction="http://tempuri.org/IHomeService/GetLengthResponse")]
        string GetLength(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetLength", ReplyAction="http://tempuri.org/IHomeService/GetLengthResponse")]
        System.Threading.Tasks.Task<string> GetLengthAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/TestMessage", ReplyAction="http://tempuri.org/IHomeService/TestMessageResponse")]
        System.ServiceModel.Channels.Message TestMessage(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/TestMessage", ReplyAction="http://tempuri.org/IHomeService/TestMessageResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> TestMessageAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHomeServiceChannel : WCFClient.HomeService.IHomeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeServiceClient : System.ServiceModel.ClientBase<WCFClient.HomeService.IHomeService>, WCFClient.HomeService.IHomeService {
        
        public HomeServiceClient() {
        }
        
        public HomeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLength(string name) {
            return base.Channel.GetLength(name);
        }
        
        public System.Threading.Tasks.Task<string> GetLengthAsync(string name) {
            return base.Channel.GetLengthAsync(name);
        }
        
        public System.ServiceModel.Channels.Message TestMessage(System.ServiceModel.Channels.Message request) {
            return base.Channel.TestMessage(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> TestMessageAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.TestMessageAsync(request);
        }
    }
}
