//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.SecondService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecondService.ISecondService")]
    public interface ISecondService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecondService/GetStrLength", ReplyAction="http://tempuri.org/ISecondService/GetStrLengthResponse")]
        int GetStrLength(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecondService/GetStrLength", ReplyAction="http://tempuri.org/ISecondService/GetStrLengthResponse")]
        System.Threading.Tasks.Task<int> GetStrLengthAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecondServiceChannel : WCFClient.SecondService.ISecondService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecondServiceClient : System.ServiceModel.ClientBase<WCFClient.SecondService.ISecondService>, WCFClient.SecondService.ISecondService {
        
        public SecondServiceClient() {
        }
        
        public SecondServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecondServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecondServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecondServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetStrLength(string str) {
            return base.Channel.GetStrLength(str);
        }
        
        public System.Threading.Tasks.Task<int> GetStrLengthAsync(string str) {
            return base.Channel.GetStrLengthAsync(str);
        }
    }
}
